# Generated by Django 3.2.6 on 2021-08-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateTimeField(verbose_name='Date of birth')),
                ('gender', models.CharField(max_length=1, verbose_name='Gender')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='Phone Number')),
                ('address', models.TextField(verbose_name='Address')),
            ],
        ),
    ]
